# Generated by Django 5.2.6 on 2026-06-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.JSONField()),
            ],
            options={
                'verbose_name': 'Порядок ответов',
                'verbose_name_plural': 'Порядки ответов',
            },
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
