# Generated by Django 5.2.6 on 2026-06-09 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_answerorder_studentanswer_reviewed_at'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_answers', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='teacher_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий преподавателя'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='teacher_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Балл преподавателя'),
        ),
        migrations.AddField(
            model_name='answerorder',
            name='student_answer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer_order', to='exams.studentanswer'),
        ),
    ]
