# Generated by Django 5.2.6 on 2026-06-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_studentanswer_reviewed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswer',
            name='is_correct',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
