# Generated by Django 5.2.6 on 2026-06-09 19:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_studentanswer_is_correct_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsubject',
            name='medium_closed_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Средние закрытые'),
        ),
        migrations.AddField(
            model_name='examsubject',
            name='medium_open_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Средние открытые'),
        ),
    ]
